### ISSUE TITLE
fix: 页脚 Powered by 取值过期

### ISSUE THREAD

**Issue by iugo** [sonofmagic/icebreaker.top#8]
应该已经切换到 supabase 了, 但是页脚代码没变:

https://github.com/sonofmagic/icebreaker.top/blob/99320ed9a56d8c0fa21460de6c711643ccec4c5f/packages/%40som/blog/client/components/layout/Footer.vue#L23-L29

应该还有其他地方也需要改, 只是提一个最常用的.

**Comment by sonofmagic** [comment]
是的，之前试过的BaaS产品比较多，忘记改了，多谢提醒
